version: '3'

services:
        node:
                build: ./node
                container_name: node
                networks:
                        - web
                environment:
                        port: 8080
                depends_on:
                        - db
                ports:
                        - 8080:8080
                working_dir: '/app'
                command: 'npm start'
                


        db:
                image: mysql:latest
                container_name: db
                networks:
                        - web
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: matcha_db
                        MYSQL_USER: yaitalla
                        MYSQL_PASSWORD: supersecretmatcha
                volumes:
                        - './db/data:/var/lib/mysql'
                        - './db/config:/etc/mysql/conf.d'
                ports:
                        - 3306:3306

networks:
        web:
                external: true
